name: Nuget
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET 8
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            - name: Setup .NET 9
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x

            - name: Restore signing key
              run: |
                  echo "$SIGN_KEY" | base64 --decode > SignKey.snk
              env:
                  SIGN_KEY: ${{ secrets.SIGN_KEY }}

            - name: Restore
              run: dotnet restore

            - name: Build (Release)
              run: dotnet build src/OpenTracing.Contrib.NetCore/OpenTracing.Contrib.NetCore.csproj --no-restore --configuration Release

            - name: Pack (Release with symbols)
              run: dotnet pack src/OpenTracing.Contrib.NetCore/OpenTracing.Contrib.NetCore.csproj --no-build --configuration Release --include-symbols --include-source -o ./nupkg

            - name: Push to NuGet
              run: |
                  dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
